name: 'Publish Docker Image'
description: 'Build Docker image and push to repository. Quay.io is a default repository'
inputs:
  registry:
    required: false
    description: 'Registry to use'
  username:
    required: true
    description: 'Registry username'
  password:
    required: true
    description: 'Registry password'
  image:
    required: true
    description: 'Docker image name'
  tag:
    required: true
    description: 'Docker image tag to use'
  tag_latest:
    required: true
    description: 'Will also add tag "latest"'
  docker_context:
    required: false
    description: 'Docker context'
  dockerfile:
    required: false
    description: 'Path to Dockerfile'

runs:
  using: 'composite'
  steps:
    - name: Login to repository
      id: repositorylogin
      uses: docker/login-action@v2
      with:
        registry: ${{ inputs.registry || 'quay.io' }}
        username: ${{ inputs.username }}
        password: ${{ inputs.password }}
   
    - name: Set up QEMU
      id: quemusetup
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      id: setupbuildx
      uses: docker/setup-buildx-action@v2

    - name: Calculate metadata
      id: metadata
      uses: docker/metadata-action@v4
      with:
        images: ${{ inputs.image }}
        tags: |
          type=raw,value=${{ inputs.tag }}
          type=raw,value=latest,enable=${{ inputs.tag_latest || false }}
    
    - name: Push container
      uses: docker/build-push-action@v4
      with:
        context: ${{ inputs.docker_context || . }}
        file: ${{ inputs.dockerfile || ./Dockerfile }}
        platforms: linux/amd64,linux/arm64
        push: true
        tags: ${{ steps.metadata.outputs.tags }}
        labels: ${{ steps.metadata.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max